tap "anomalyco/tap", trusted: { formulae: ["opencode"] }
# Incredibly fast JavaScript runtime, bundler, test runner, and package manager
brew "bun"
# Agent multiplexer that lives in your terminal
brew "herdr"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
cargo "docpars"
npm "corepack"
